const UPDATE_LIST_BUTTON = document.querySelector('.update-list-button'),
      CONTROL_BAR_NODE = document.querySelector('.control-bar'),
      CREATE_BUTTON = document.querySelector('.create-button'),
      UPDATE_BUTTON = document.querySelector('.update-button'),
      DELETE_BUTTON = document.querySelector('.delete-button'),
      CREATE_CONTROL = document.querySelector('.create-control'),
      UPDATE_CONTROL = document.querySelector('.update-control'),
      DELETE_CONTROL = document.querySelector('.delete-control'),
      LIST = document.querySelector('.list');